### PR TITLE
Major code refactoring courtesy of Gustavo

### PR DESCRIPTION
**Pull request by raidancampbell**
Major code changes, largely to the javascript.  Some highlights are as follows:
- Renamed a lot stuff
- Tried to standardize some stuff
- Removed duplicate code.
- Removed the pooling system from NvHTTP
- Removed the app box cache from NvHTTP

This is not ready for immediate merging, but was created for discussion as we prepare for merging.

### CODE REVIEW

**Comment by cgutman** [comment]
Please don't merge this until I've been able to review it.

**Comment by raidancampbell** [comment]
After quitting a stream, the box art isn't stylized to indicate the currently running app, and the `quit current app` doesn't show up.  Re-entering the host selection screen shows proper behavior

**Comment by dead** [comment]
I was going to squash the commits before submit the pull request, but thanks 😄 

> After quitting a stream, the box art isn't stylized to indicate the currently running app, and the quit current app doesn't show up. Re-entering the host selection screen shows proper behavior.
> 
> Additionally, after stopping the current app, the box art does not restylize to indicate it is no longer running

Already fixed it but I'm gonna wait @cgutman review the code before submit a new commit.

**Comment by raidancampbell** [comment]
@dead are you finished committing on this?  I'd like to find some time within the coming weeks to fully test and merge it.

**Comment by dead** [comment]
There is some stuff that I want to discuss with you guys.
- When refresh the app list cache
- Why/When use the hostname as the address
- And if you guys think there is something in the code that need be changed or improved

**Comment by raidancampbell** [comment]
Unfortunately, I let this grow stale and fall through the cracks.  Sorry

**Pull request closed without merging**
