### PR TITLE
Add 16:10 resolution options. 

### PR DESCRIPTION
**Pull request by jeid64**
I have a 16:10 laptop, having black bars on the top and bottom of my screen were driving me crazy. I added two 16:10 ratios, choosing 1920x1200 and 1280x800.

I wanted to also add 1440x900, but the RTSP stream would fail to be started if that was chosen. Any ideas why?

### CODE REVIEW

**Comment by raidancampbell** [comment]
When I was poking around with 4K support, I accidentally swapped the x and y resolutions, which caused the same RTSP handshake failure that you saw: could you double check for that issue?

Additionally, what version of GFE are you using?  If I recall correctly, the beta version is required for 4K, so certain resolutions may not work on the mainline GFE versions.  I'd like to know if GFE truly doesn't support 1440x900 or if some minor issue is to blame, before merging this in.

I don't have any issues merging additional resolutions in, as the current UI keeps the options clean.  @cgutman what are your opinions?

**Comment by jeid64** [comment]
Double checked, it is failing on 1440x900, made sure X and Y isn't swapped. I'm on 2.11.2.67, which is the beta GFE. 1920x1200 and 1280x800 worked fine though. It's odd to me that 1440x900 wouldn't work, I initially thought it might be too low of a resolution but it has more pixels than 720p which works fine. Is there a way to debug why the RTSP stream fails to initialize?

**Comment by cgutman** [comment]
What you're seeing is the reason that we haven't added any non-officially supported resolutions to Moonlight clients yet. For resolutions other than 720p, 1080p, and 4K, the GFE server will fail to establish a connection if it can't set the physically connected PC display to match the requested resolution. 4K has a special exception to this rule which lets GFE set the PC display to 1080p if 4K is requested and stream 4K to clients.

**Comment by jeid64** [comment]
@cgutman is a 100% right, just realized my physically connected display cannot be set to 1440x900.

Is there anyway to poll for available monitor resolutions? Otherwise, this merge will break people who try to use the new two resolutions but their monitors cannot be set to it. I noticed that /serverinfo returns back Supported Resolutions of 720p and 1080p to the client, but not any other possible resolutions.

**Comment by jeid64** [comment]
Sadly, this current pull request shouldn't be merged due to Nvidia not reporting monitor resolution.

Would an "advanced" setting that allows people to try and set whatever resolution they want with an explanation of it needing to match an available monitor resolution be good? Or is this option not really needed?

**Comment by raidancampbell** [comment]
I'm not a big fan of having more "advanced" settings than required: this feels like a clumsy solution for a feature for a smaller portion of the user base.  Thanks for the contribution and looking into this, but I'm closing the PR.

**Pull request closed without merging**
