### PR TITLE
Host chooser style overhaul + host IP display

### PR DESCRIPTION
**Pull request by andrew-anguiano**
I updated the style of the plugin (namely the host selection page/grid) to have more of a "Material-esque" feel. There are still a few more tweaks I'd like to do, but I think this is a good start. I updated a few of the JS calls to properly utilize the new elements as well.

Additionally, I added the host IP information below the hostname. I ran into an issue when I had a host with both and internal IP address and added again with a no-ip domain name. I couldn't tell them apart, so I felt adding the IP info back into the plugin would be useful.

screen shot 2016-08-07 at 11 04 26 pm

### CODE REVIEW

**Comment by raidancampbell** [comment]
I'm going to hold off on merging this: the reason we went with the less material grid selection was to replicate the UI on the Android client.

The IP replication issue is noted in #71 and closely coupled with #53, the behavior you see is not intended behavior.

I really appreciate the work, and definitely welcome additional influence on the code: I've never written any HTML/CSS/JS before, so commits from anyone with previous experience is extremely useful.  If you'd like to give me a hand with that, I welcome you to take a look at #32 and #73.

**Comment by ShadowBullet** [comment]
I quite like the material design, I think it fits chrome. IMO the Moonlight client for Android should also be more Material-esqe, however that's just one guy's opinion. I have always tended like material design themed things.

**Comment by andrew-anguiano** [comment]
Thanks @raidancampbell! No problem - I set out to add the IP and ended up sort of hacking away at the interface. 

I'll take a look at those issues in my spare time. I'm more of a front-end guy so maybe I can help out. 

I would agree with @ShadowBullet that perhaps the Android UI should be updated to a more material theme to keep in step with the Android OS UI, but that's just my opinion. Should I go ahead and close this pull request?

**Comment by raidancampbell** [comment]
Thanks for hacking away at the interface, the code's been turning into spaghetti because I've had my hands in it too much: it's really valuable to me for someone else to look at the code.

Don't close the PR quite yet, I'll talk it over and see what other people think

**Comment by andrew-anguiano** [comment]
I'll gladly take a look when I get a chance. As someone who uses Moonlight almost daily, I'm excited to contribute any way I can.

**Comment by raidancampbell** [comment]
Closed, having a common UI across the clients is more important than sticking to Material guidelines.  Thanks for your contribution

**Pull request closed without merging**
